name: Latest blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 15 * * *'
  workflow_dispatch:
  
env:
  TEMPLATE: "$newline- $date - [$title]($url)"
  DATE_FORMAT: "UTC:mmm dd yyyy"
  COMMITTER_EMAIL: "dipien2020@gmail.com"
  COMMITTER_USERNAME: "dipien-ci"

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Android Developers - Medium Publication
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "ANDROID_DEVS_MEDIUM"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "https://medium.com/feed/androiddevelopers"
          commit_message: "Updated with the latest Android Developors Medium posts"
      - name: Firebase Developers - Medium Publication
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "FIREBASE_DEVS_MEDIUM"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "https://medium.com/feed/firebase-developers"
          commit_message: "Updated with the latest Firebase Developers Medium posts"
      - name: Google Play - Medium Publication
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "GOOGLE_PLAY_MEDIUM"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "https://medium.com/feed/googleplaydev"
          commit_message: "Updated with the latest Google Play Medium posts"
      - name: Android Developers - Youtube Channel
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "ANDROID_YOUTUBE"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCVHFbqXqoYvEWM1Ddxl0QDg"
          commit_message: "Updated with the latest Android Developors Youtube videos"
      - name: Firebase - Youtube Channel
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "FIREBASE_YOUTUBE"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCP4bf6IHJJQehibu6ai__cg"
          item_exec: |
                    console.log("post.title");
                    post.title = post.title.replace('|','\|');
                    console.log("post.title");
          
          commit_message: "Updated with the latest Firebase Youtube videos"
      - name: Material Design - Youtube Channel
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "MATERIAL_DESIGN_YOUTUBE"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCcnSNQb0tLVd8uT7gzI8duA"
          commit_message: "Updated with the latest Material Design Youtube videos"
      - name: Android Developers Blog
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "ANDROID_DEVS_BLOG"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "https://android-developers.blogspot.com/atom.xml"
          commit_message: "Updated with the latest Android Developors Blog posts"
      - name: The Firebase Blog
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "FIREBASE_BLOG"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "https://firebase.googleblog.com/atom.xml"
          commit_message: "Updated with the latest Firebase Blog posts"
      - name: Material Design Blog
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "MATERIAL_DESIGN_BLOG"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "https://material.io/feed.xml"
          commit_message: "Updated with the latest Material Design Blog posts"
      - name: Android Developers Backstage - Podcasts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "ANDROID_DEVS_BACKSTAGE"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "http://adbackstage.googledevelopers.libsynpro.com/rss"
          commit_message: "Updated with the latest Android Developors Backstage podcats"
          
