name: Latest blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "MEDIUM"
          date_format: "UTC:ddd mmm dd yyyy"
          template: "$newline- $date [$title]($url)"
          feed_list: "https://medium.com/feed/androiddevelopers"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "YOUTUBE"
          date_format: "UTC:ddd mmm dd yyyy"
          template: "$newline- $date [$title]($url)"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCVHFbqXqoYvEWM1Ddxl0QDg"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "BLOG"
          date_format: "UTC:ddd mmm dd yyyy"
          template: "$newline- $date [$title]($url)"
          feed_list: "https://android-developers.blogspot.com/atom.xml"
