name: Latest blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 */1 * * *'
  workflow_dispatch:
  
env:
  TEMPLATE: "$newline- $date - $feed - [$title]($url)"
  DATE_FORMAT: "UTC:mmm dd yyyy"
  COMMITTER_EMAIL: "dipien2020@gmail.com"
  COMMITTER_USERNAME: "dipien-ci"
  ITEM_EXEC: "post.title = post.title.replace('|','-');if (post.url.startsWith('https://www.youtube.com')) {  post.feed = 'Youtube' };"

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: News
        # https://github.com/gautamkrishnar/blog-post-workflow
        uses: gautamkrishnar/blog-post-workflow@1.5.7
        with:
          max_post_count: "100"
          comment_tag_name: "NEWS"
          date_format: ${{ env.DATE_FORMAT }}
          template: ${{ env.TEMPLATE }}
          committer_username: ${{ env.COMMITTER_USERNAME }}
          committer_email: ${{ env.COMMITTER_EMAIL }}
          feed_list: "https://medium.com/feed/androiddevelopers,https://medium.com/feed/firebase-developers,https://medium.com/feed/googleplaydev,https://www.youtube.com/feeds/videos.xml?channel_id=UCVHFbqXqoYvEWM1Ddxl0QDg,https://www.youtube.com/feeds/videos.xml?channel_id=UCP4bf6IHJJQehibu6ai__cg,https://www.youtube.com/feeds/videos.xml?channel_id=UCcnSNQb0tLVd8uT7gzI8duA,https://android-developers.blogspot.com/atom.xml,https://firebase.googleblog.com/atom.xml,https://material.io/feed.xml,http://adbackstage.googledevelopers.libsynpro.com/rss"
          item_exec: ${{ env.ITEM_EXEC }}
          custom_tags: "feed/feed/"
          commit_message: "Updated with the latest news"
